# Generated by Django 5.2.10 on 2026-01-23 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wishlist", "0002_rename_added_at_wishlist_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wishlist",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="wishlistitem",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
